### ISSUE TITLE
Quick repair of daggers = shovel

### ISSUE THREAD

**Issue by WardsParadox** [SpluoSplatus/Spellbound-Weapons#1]
Not sure if a recipe collision or bug, but if you try to repair two daggers in the crafting table, they combine into a shovel.

**Comment by limesplatus** [comment]
> Not sure if a recipe collision or bug, but if you try to repair two daggers in the crafting table, they combine into a shovel.

Recipe collision, if you want to repair a dagger by merging it with another dagger use a grindstone

**Comment by WardsParadox** [comment]
Ok..shouldn't it still not offer a shovel? It seems like the quick repair options should be disabled

**Comment by limesplatus** [comment]
Correct, it really shouldn’t but it’s a limitation of datapacks (if you didnt know the mod version of spellbound weapons is just a datapack packaged into a mod)

**Comment by WardsParadox** [comment]
Ah TIL. Thanks for the info.
